---
- name: Example Ansible Playbook
  hosts: all
  become: yes

  tasks:
    - name: Ensure the latest version of git is installed
      apt:
        name: git
        state: latest
        update_cache: yes

    - name: Create a directory
      file:
        path: /home/username/example_directory
        state: directory
        mode: '0755'

    - name: Copy a file
      copy:
        src: /home/username/source_file.txt
        dest: /home/username/example_directory/destination_file.txt